package com.yzdev.sportome.domain.use_case.favoriteCompetition

import com.yzdev.sportome.domain.use_case.favoriteCompetition.deleteFavoriteCompetition.DeleteFavoriteCompetitionUseCase
import com.yzdev.sportome.domain.use_case.favoriteCompetition.getAllFavoriteCompetition.GetAllLocalFavoriteCompetitionUseCase
import com.yzdev.sportome.domain.use_case.favoriteCompetition.getLocalFavoriteCompetitionById.GetFavoriteCompetitionUseCase
import com.yzdev.sportome.domain.use_case.favoriteCompetition.insertFavoriteCompetition.InsertFavoriteCompetitionUseCase

data class CompetitionUseCaseFormat(
    val insertFavoriteCompetition: InsertFavoriteCompetitionUseCase,
    val getAllLocalFavoriteCompetitionUseCase: GetAllLocalFavoriteCompetitionUseCase,
    val getFavoriteCompetitionUseCase: GetFavoriteCompetitionUseCase,
    val deleteFavoriteCompetitionUseCase: DeleteFavoriteCompetitionUseCase
)
